#!/bin/bash -e

ORG_PATH="github.com/coreos"
REPO_PATH="${ORG_PATH}/etcd-starter"

export GOPATH=${PWD}/gopath

rm -f $GOPATH/src/${REPO_PATH}
mkdir -p $GOPATH/src/${ORG_PATH}
ln -s ${PWD} $GOPATH/src/${REPO_PATH}

eval $(go env)

# Static compilation is useful when etcd-starter is run in a container
CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-s' -o bin/etcd-starter ${REPO_PATH}
